/**
 * Every string a person reads, in one place. Code is English (project convention); the interface
 * is pt-BR, which is the only locale today — this module is the seam if that ever changes.
 */
export const t = {
  appName: 'Treasurer',

  event: {
    newEvent: 'Novo rolê',
    name: 'Nome do rolê',
    date: 'Data',
    create: 'Criar rolê',
    expenses: 'Despesas',
    addExpense: 'Adicionar despesa',
    description: 'Descrição',
    amount: 'Valor cobrado',
    receiptTotal: 'Valor da nota',
    receiptTotalHint: 'Só se for diferente do cobrado — quem comprou arredondou pra baixo.',
    note: 'nota',
    paidBy: 'Quem pagou e recebe',
    club: 'Caixa do clube',
    whoIsIn: 'Quem entra nessa',
    whoIsInHint: 'Desmarque quem não entra — a linha aparece zerada pra pessoa, nunca some.',
    without: 'sem',
    collectionKey: 'Chave pix pra receber',
    collectionKeyHint: 'Opcional. Aparece pra quem tem que te pagar.',
    whoCame: 'Quem foi',
    total: 'Total',
    noExpenses: 'Nenhuma despesa ainda.',
    remove: 'Remover',
    publish: 'Fechar rateio e liberar os valores',
    published: 'Valores liberados para os membros',
    settle: 'Encerrar o rolê',
    settleHint:
      'Depois disso ninguém mexe mais nas despesas. O que ficou em aberto continua em aberto.',
    openEvents: 'Rolês abertos',
    past: 'Rolês anteriores',
    noEvents: 'Nenhum rolê ainda. Crie o primeiro aí em cima.',
    closed: 'Encerrado',
    open: 'Em aberto',
    backToPanel: 'Voltar',
    saveRoster: 'Salvar quem foi',
    about: 'Sobre o rolê',
    aboutField: 'Descrição',
    aboutHint: 'Onde é, o que levar, o que mais o pessoal precisa saber. Aparece no link do rolê.',
    saveAbout: 'Salvar',
    edit: 'Editar',
    saveExpense: 'Salvar despesa',
    cancel: 'Cancelar',
    correctionHint:
      'Enquanto o rolê está aberto dá pra corrigir despesa e quem foi. Quem já pagou entra em conferência.',
    addGuest: 'Adicionar convidado',
    guestName: 'Nome do convidado',
    guest: 'convidado',
    members: 'Membros',
  },

  settlement: {
    member: 'Membro',
    code: 'Cód',
    share: 'Parte',
    toPay: 'A pagar',
    receives: 'Recebe',
    collectors: 'Quem recebe',
    collecting: 'A receber',
    rounding: 'Arredondamento pra cima',
    paid: 'Recebido',
    markPaid: 'Marcar como recebido',
    markReimbursed: 'Marcar como devolvido',
    reimbursed: 'Devolvido',
    copy: 'Copiar resumo pro zap',
    copied: 'Copiado!',
    needsReview: 'Conferir',
    needsReviewHint:
      'O valor mudou depois que essa pessoa pagou. Confira a diferença antes de dar como quitado.',
    short: 'falta entrar',
    toReturn: 'a devolver',
  },

  share: {
    tapYourName: 'Toque no seu nome',
    link: 'Link do rolê',
    copyLink: 'Copiar link do rolê',
    share: 'Compartilhar no zap',
    people: 'pessoas',
  },

  member: {
    yourShare: 'Sua parte',
    roundedUp: 'Arredondado pra cima pros centavos fecharem com a nota.',
    roundingKept: 'Arredondamento recebido',
    toPay: 'A pagar',
    payTo: 'Pra quem pagar',
    youReceive: 'Você recebe',
    settled: 'Você está quitado',
    exact: 'Pague o valor exato, sem arredondar.',
    broughtOwn: 'você trouxe a sua',
    notReady: 'O rateio ainda está sendo fechado. Volte daqui a pouco.',
    changed: 'O valor mudou depois do seu pagamento. O clube vai conferir.',
  },

  admin: {
    title: 'Membros',
    add: 'Adicionar membro',
    name: 'Nome',
    retire: 'Marcar como saiu',
    retired: 'Saiu do clube',
  },

  errors: {
    badAmount: 'Valor inválido. Escreva assim: 158,73',
    required: 'Preencha este campo',
    noAccess: 'Link inválido ou expirado.',
    closed: 'Esse rolê já foi encerrado. Não dá mais pra mexer nas despesas.',
    createFailed: 'Não deu pra criar o rolê. O banco pode estar desatualizado.',
  },
} as const;
